services:
  postgres:
    image: postgres:18.3-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: example

volumes:
  postgres-data:
